### PR TITLE
Bug fixing

### LINKED ISSUE #113: After ViewPager Addition, Bottom navigation view's actions aren't working properly.
Steps to reproduce bug
1) When Clicking an image in scrolling fragment  we reach to full_image_fragment ( say image1 ) which has viewpager . 
2) In ViewPager, slide left or right to see other images.
3) Click on any action of Bottom navigation view, It will display previous image (which was loaded in step i.e image1) details and perform action on it instead of new Image which is getting displayed in viewpager.

### PR DESCRIPTION
**Pull request by SB2318**
Fixes #113 
Bugs Which are removed:
1. Except for a few cases, we're able to access right image in most of the cases.
2. Sliding left or right probably now showing the correct image.

Bugs, which could not be removed due to lack of function.
1. Uploaded icon is not changed, because there must be a function isUploaded() which is now in under construction. (But images are uploaded, please check the database.)

Bugs which are still remaining:
Favourite icon action.
Further, if there is a problem let me know.

### CODE REVIEW

File: app/src/main/java/com/example/gallery/FullImageFragment.kt [hunk 1]
```diff
@@ -417,6 +422,13 @@ class FullImageFragment : Fragment() {
             var imageView = itemLayout.findViewById<ZoomageView>(R.id.fullimageViewid)
             imageView.setImageURI(Uri.parse(imageList[position]))
 
+            var currPos= if(position==imageList.size-1 || position==0)
```
Comment (vivekgupta4Git) [inline app/src/main/java/com/example/gallery/FullImageFragment.kt:425]: For Viewpager, currPos will have value 2. It is because viewpager will call instantiateItem() method for three times. For position 1 then for 0 and 2.  This is default behaviour of viewPager see documentation for further knowledge about offScreenPageLimit which has minimum value of 1. We can't do much here , position variable will us wrong information. 
So, try moving this logic on page selected listener. I guess, it might work.

Comment (SB2318) [reply app/src/main/java/com/example/gallery/FullImageFragment.kt:425]: Yeah, Thanks 👍. But @vilgad told that he has some another logic to fixed it.

Comment (vivekgupta4Git) [reply app/src/main/java/com/example/gallery/FullImageFragment.kt:425]: Cool

**Comment by SB2318** [comment]
@vilgad accept my this PR, otherwise I have to close it , because maybe I should submit another job today with demo and please change the title of another issue which is assigned to me.
